# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                        # Nombre de liens affichés dans le menu de pagination
    default_options:
        page_name: page                  # Nom du paramètre de requête pour la page
        sort_field_name: sort            # Nom du paramètre de requête pour le champ de tri
        sort_direction_name: direction   # Nom du paramètre de requête pour la direction du tri
        distinct: true                   # Assure des résultats distincts, utile lorsque les requêtes ORM utilisent des instructions GROUP BY
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Template de pagination pour Bootstrap 5
