_locale_prefix:
    requirements:
        _locale: fr|es
    defaults:
        _locale: fr
    type: attribute
    prefix: /{_locale}
    resource:
        path: ../src/Controller/
        namespace: App\Controller
