name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer la connexion SSH
      - name: Set up SSH connection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host hostinger" >> ~/.ssh/config
          echo "  HostName 195.35.49.40" >> ~/.ssh/config
          echo "  User u910560794" >> ~/.ssh/config
          echo "  Port 65002" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

      # Étape 3 : Déployer le projet Symfony via SSH
      - name: Deploy to Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no hostinger << 'EOF'
            cd /home/u910560794/domains/massgrafik.com/public_html
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php bin/console cache:clear --env=prod
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod
          EOF
